Repository jenkins-x/ext-java-code-quality, pull requests merged in 2018-10, with the labels that each got.

#1 setup CI/CD with serverless Jenkins
  Jenkinsfile
Labels: approved, size/M

#10 fix: oops, wrong dir
  Jenkinsfile
Labels: approved, size/XS

#11 feat: support repository file too
  updatebot.sh
Labels: approved, size/XS

#12 fix: correct GitHub org name
  Jenkinsfile
  updatebot.sh
Labels: approved, size/XS

#15 Fix: fix regex for updatebot
  updatebot.sh
Labels: approved, size/XS

#17 Updatebot6
  .dockerignore
  .helmignore
  Dockerfile
  Makefile
  charts/ext-java-code-quality/.helmignore
  charts/ext-java-code-quality/Chart.yaml
  charts/ext-java-code-quality/Makefile
  charts/ext-java-code-quality/README.md
  charts/ext-java-code-quality/templates/NOTES.txt
  charts/ext-java-code-quality/templates/_helpers.tpl
  charts/ext-java-code-quality/templates/deployment.yaml
  charts/ext-java-code-quality/templates/service.yaml
  charts/ext-java-code-quality/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  curlloop.sh
  skaffold.yaml
  updatebot.sh
  watch.sh
Labels: approved, size/L
